#!/bin/bash

databaseToBackup=$1
databasesContainer=${instance}Databases
accountsContainer=${instance}AccountsDatabase
backupDirectory=~/${instance}/backupDirectory

rm -rf "$backupDirectory"

if [ -n "$databaseToBackup" ]; then
    mkdir -p $backupDirectory/databases
    echo "----------------------------"
    echo "----------------------------"
    echo "Backing up $databaseToBackup ..."
    echo "----------------------------"
    echo "----------------------------"
    docker exec $databasesContainer bash -c "rm -rf /tmp/$databaseToBackup.archive"
    docker exec $databasesContainer mongodump \
        --username=${databasesUser} \
        --password=${databasesPassword} \
        --authenticationDatabase=admin \
        --db=$databaseToBackup \
        --archive=/tmp/$databaseToBackup.archive \
        --gzip
    docker cp $databasesContainer:/tmp/$databaseToBackup.archive $backupDirectory/databases/$databaseToBackup.archive 1>/dev/null
    echo "Backup complete for $databaseToBackup"
    exit 0
fi

echo "----------------------------"
echo "----------------------------"
echo "Backing up ${instance} ..."
echo "----------------------------"
echo "----------------------------"

mkdir -p $backupDirectory/databases

docker exec $databasesContainer bash -c "mongosh --quiet --username \"${databasesUser}\" --password \"${databasesPassword}\" --authenticationDatabase admin --eval 'db.adminCommand({ listDatabases: 1 }).databases.map(d => d.name).join(\"\n\")'" |
while read database; do
    if [[ $database == admin || $database == local || $database == config ]]; then
        continue
    fi
    docker exec $databasesContainer bash -c "rm -rf /tmp/$database.archive"
    docker exec $databasesContainer mongodump \
        --username=${databasesUser} \
        --password=${databasesPassword} \
        --authenticationDatabase=admin \
        --db=$database \
        --quiet \
        --archive=/tmp/$database.archive \
        --gzip
    docker cp $databasesContainer:/tmp/$database.archive $backupDirectory/databases/$database.archive 1>/dev/null
    echo $database
done

if [ -d ~/${instance}/accounts ]; then
    mkdir -p $backupDirectory/accounts/databases
    docker exec $accountsContainer bash -c "rm -rf /tmp/keycloak.sql"
    docker exec $accountsContainer bash -c "mariadb-dump -u ${accountsMariaUser} -p${accountsMariaPassword} accounts > keycloak.sql"
    docker cp $accountsContainer:/tmp/keycloak.sql $backupDirectory/accounts/databases/keycloak.sql 1>/dev/null
    echo "Accounts database"
fi

echo "Copying non-database files ..."
rsync -a --no-times \
    --exclude="backupDirectory/" \
    --exclude="databases/" \
    ~/${instance}/ $backupDirectory/

timestamp=$(date +%Y-%m-%d_%H-%M-%S)
echo "Uploading ..."
if ( which azcopy 1>/dev/null ); then
    azcopy copy "$backupDirectory/*" "https://${azureStorage}.blob.core.windows.net/backup/$timestamp/$}sas}" --recursive=true 1>/dev/null
else
    /azcopy copy "$backupDirectory/*" "https://${azureStorage}.blob.core.windows.net/backup/$timestamp/$}sas}" --recursive=true 1>/dev/null
fi
echo "Uploaded"

echo "Deleting old backups ..."
retainingDates=()
for i in {0..29}; do
    retainingDates+=($(date -d "-$i days" +%Y-%m-%d))
done
for i in {30..119}; do
    day=$(date -d "-$i days" +%Y-%m-%d)
    if [ $(date -d "$day" +%u) -eq 6 ]; then
        retainingDates+=($day)
    fi
done
for i in {30..119}; do
    retainingDates+=($(date -d "-$i days" +%Y-%m-01))
done
for i in {4..12}; do
    retainingDates+=($(date -d "-$i months" +%Y-%m-01))
done
export retainingDates=($(echo "${retainingDates[@]}" | tr ' ' '\n' | sort -u))

for date in "${retainingDates[@]}"; do
    echo $date
done

blobs=$(az storage blob list --account-name ${azureStorage} --container-name backup --sas-token "$}sas}" --query "[].name" -o tsv)
for blob in $blobs; do
    keep=false
    for date in "${retainingDates[@]}"; do
        if [[ $blob == $date* ]]; then
            keep=true
            break
        fi
    done

    if [ "$keep" = false ]; then
        echo "Deleting blob: $blob"
        az storage blob delete --account-name ${azureStorage} --container-name backup --name "$blob" --sas-token "$}sas}"
    else
        echo "Keeping blob: $blob"
    fi
done

echo "Deleted old backups"
date >> ~/$instance/backupLog
