#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    docker container ls -a --format "table {{.ID}}\t{{.Image}}\t{{.RunningFor}}\t{{.Status}}\t{{.Names}}"
else
    docker container ls -a --format "table {{.ID}}\t{{.Image}}\t{{.RunningFor}}\t{{.Status}}\t{{.Names}}" | grep "$1"
fi
