#!/usr/bin/env node

import {
    createDirIfNotExists,
    excludedDirs,
    getDepth,
    getDirs,
} from '../scripts/os.js'
import {
    divide,
    errorAndExit,
    info,
} from '../scripts/logger.js'
import loadGeneratorSettings from '../scripts/loadGeneratorSettings.js'
import generateForDirectory from '../scripts/generateForDirectory.js'
import extract from '../scripts/extract.js'
import { clear } from '../scripts/terminal.js'
import generateBackupAndRestore from '../scripts/generateBackupAndRestore.js'
import parseGenerateArguments from '../scripts/parseGenerateArguments.js'
import readGeneratorTenants from '../scripts/readGeneratorTenants.js'

if (process.getuid?.() === 0) {
    errorAndExit('This command must not be run by the root user')
}

clear()

const findDirectories = () => {
    const dirs = getDirs().filter(d => !excludedDirs.includes(d))
    return dirs.sort()
}

const validateDepth = params => {
    const { baseDir } = params
    if (baseDir === '/') {
        errorAndExit('Can not be executed from the root')
    }
    const depth = getDepth(baseDir)
    params.depth = depth
    if (depth !== 3) {
        errorAndExit('This command must be run from depth 3 (i.e. ~/instance)')
    }
}

const baseDir = process.cwd()
const params = loadGeneratorSettings(baseDir)
params.baseDir = baseDir
params.home = process.env.HOME
params.user = process.env.USER
validateDepth(params)

const tenantNames = parseGenerateArguments(process.argv.slice(2))
const directories = findDirectories()
const tenants = readGeneratorTenants(tenantNames)
params.tenantOnly = tenantNames.length > 0
let needsCache = false
for (const directoryName of directories) {
    const p = `${baseDir}/${directoryName}`
    params.directoryName = directoryName
    params.directoryPath = p
    params.depth = getDepth(params.directoryPath)
    process.chdir(p)
    divide()
    info(directoryName)
    divide()
    const generatedParams = generateForDirectory({
        ...params,
        tenants,
    })
    needsCache = needsCache || ['api', 'site'].includes(generatedParams.file)
    process.chdir(baseDir)
}

if (needsCache && !params.tenantOnly && !directories.includes('cache')) {
    const directoryName = 'cache'
    const directoryPath = `${baseDir}/${directoryName}`
    createDirIfNotExists(directoryPath)
    process.chdir(directoryPath)
    divide()
    info(directoryName)
    divide()
    generateForDirectory({
        ...params,
        directoryName,
        directoryPath,
        depth: getDepth(directoryPath),
        tenants,
    })
    process.chdir(baseDir)
}

divide()
if (!params.tenantOnly) {
    params.directoryPath = baseDir
    params.depth = getDepth(baseDir)
    extract(params)
    generateBackupAndRestore(params)
}
