#!/usr/bin/env node

import os from 'os'
import { runOnTerminal } from '../scripts/terminal.js'
import { info } from '../scripts/logger.js'
import extract from '../scripts/extract.js'
import camelize from '../scripts/camelize.js'
import getComposePort from '../scripts/getComposePort.js'
import getReverseProxyPort from '../scripts/getReverseProxyPort.js'
import { getDepth } from '../scripts/os.js'

const directoryPath = process.cwd()
let params = { directoryPath }
params = extract(params)
const home = directoryPath.startsWith('/home/')
    ?
    '/' + directoryPath.split('/').slice(1, 3).join('/')
    :
    os.homedir()

params.home = home

const {
    composeFile,
    fullProcessName,
    processPath,
} = params

const processPort = getComposePort(params)
const {
    reverseProxyPort,
    runningReverseProxyPort,
} = getReverseProxyPort(params)

const pid = runOnTerminal(
    `/usr/local/node/bin/pm2 pid ${fullProcessName}`,
    true
).trim()

const runningProcessPort = pid
    ? runOnTerminal(
        `lsof -Pan -p ${pid} -iTCP -sTCP:LISTEN | awk 'NR==2 {print $9}' | sed 's/.*://'`,
        true
    ).trim()
    : ''

info(`${fullProcessName}`)
info(`runningReverseProxyPort: ${runningReverseProxyPort}`)
info(`reverseProxyPort: ${reverseProxyPort}`)
info(`runningProcessPort: ${runningProcessPort}`)
info(`processPort: ${processPort}`)
