#!/usr/bin/env node

import os from 'os'
import { runOnTerminal } from '../scripts/terminal.js'
import { info } from '../scripts/logger.js'
import extract from '../scripts/extract.js'
import camelize from '../scripts/camelize.js'
import getComposePort from '../scripts/getComposePort.js'
import getReverseProxyPort from '../scripts/getReverseProxyPort.js'
import { getDepth } from '../scripts/os.js'

const directoryPath = process.cwd()

const home = directoryPath.startsWith('/home/')
    ?
    '/' + directoryPath.split('/').slice(1, 3).join('/')
    :
    os.homedir()
let params = {
    directoryPath,
    home,
}
params = extract(params)

const {
    composeFile,
    fullProcessName,
    instance,
    process,
    processPath,
} = params

const processPort = getComposePort(params)
const {
    reverseProxyPort,
    runningReverseProxyPort,
} = getReverseProxyPort(params)

let command = `ps -eo pid,args | grep '${instance}' | grep '${process}' | grep -v grep | awk '{print $1}'`
const pid = runOnTerminal(command).trim()

command = `lsof -Pan -p ${pid} -iTCP -sTCP:LISTEN | awk 'NR==2 {print $9}' | sed 's/.*://'`
const runningProcessPort = pid
    ?
    runOnTerminal(command).trim()
    :
    ''

info(`${fullProcessName}`)
info(`runningReverseProxyPort: ${runningReverseProxyPort}`)
info(`reverseProxyPort: ${reverseProxyPort}`)
info(`runningProcessPort: ${runningProcessPort}`)
info(`processPort: ${processPort}`)
