#!/usr/bin/env node

import {
    excludedDirs,
    getDepth,
    getDirs,
    isDev,
    isFile,
} from '../scripts/os.js'
import extract from '../scripts/extract.js'
import { runOnTerminal } from '../scripts/terminal.js'

const pull = async params => {
    const {
        directoryPath,
        filter,
    } = params
    params.depth = getDepth(directoryPath)
    params.home = process.env.HOME
    params.isDev = isDev()
    params.environmentRoot = isDev() ? `${params.home}` : '/holism'
    params = extract(params)
    const {
        instancePath,
        level,
        lowercaseGitHubImageNameOrProcess,
        lowercaseInstance,
        processPath,
    } = params

    if (level === 'instance') {
        let dirs = getDirs().filter(d => !excludedDirs.includes(d))
        if (filter) {
            const regex = new RegExp(filter)
            dirs = dirs.filter(dir => regex.test(dir))
        }
        for (const dir of dirs) {
            const directoryPath = `${instancePath}/${dir}`
            await pull({
                directoryPath,
                print: true,
            })
        }
    } else {
        const composeFile = `${processPath}/compose.yaml`
        if (isFile(composeFile)) {
            const command = `docker compose -p ${lowercaseInstance}-${lowercaseGitHubImageNameOrProcess} pull`
            runOnTerminal(command)
        }
    }
}

await pull({
    filter: process.argv[2] || '',
    directoryPath: process.cwd(),
})
