#!/usr/bin/env node

import cpu from '../scripts/serverInfo/cpu.js'
import ram from '../scripts/serverInfo/ram.js'
import storage from '../scripts/serverInfo/storage.js'
import system from '../scripts/serverInfo/system.js'

system()
cpu()
ram()
storage()
