#!/usr/bin/env bash

bash "$(dirname "$0")/../setup/node"
source "$(dirname "$0")/../setup/prod"
source "$(dirname "$0")/../setup/secureUsers.sh"
source "$(dirname "$0")/../setup/setPermissions.sh"
source "$(dirname "$0")/../setup/includeUpdateTerminalTitleConfig.js"
