#!/usr/bin/env bash
set -euo pipefail

homeDir=$(getent passwd "${SUDO_USER:-$USER}" | cut -d: -f6)
setupProd="/holism/server/setupProd"
scripts="/holism/server/scripts"

export homeDir
export setupProd
export scripts

. "$scripts/logger.sh"

clear
divide
info "running setup ..."
divide

$setupProd/setup

success "setup complete"
