#!/usr/bin/env node

import { pathToFileURL } from "url"
import {
    getDepth,
    getDirs,
    isDev,
    isFile,
} from '../scripts/os.js'
import extract from '../scripts/extract.js'
import { runOnTerminal } from '../scripts/terminal.js'

const start = params => {
    const {
        filter,
        directoryPath,
    } = params
    params.depth = getDepth(directoryPath)
    params.home = process.env.HOME
    params.isDev = isDev()
    params.environmentRoot = isDev() ? `${params.home}` : '/gesht'
    params = extract(params)
    const {
        instancePath,
        level,
        lowercaseGitHubImageNameOrProcess,
        lowercaseInstance,
        processPath,
    } = params

    if (level === 'instance') {
        let dirs = getDirs(instancePath)
        if (filter) {
            const regex = new RegExp(filter)
            dirs = dirs.filter(dir => regex.test(dir))
        }
        for (const dir of dirs) {
            const directoryPath = `${instancePath}/${dir}`
            start({
                directoryPath,
            })
        }
    } else {
        const composeFile = `${processPath}/compose.yaml`
        if (isFile(composeFile)) {

            runOnTerminal('docker system prune --force')
            const command = `docker compose -p ${lowercaseInstance}-${lowercaseGitHubImageNameOrProcess} up --remove-orphans --quiet-pull -d`
            console.log(command)
        }
    }
}

const isMain = import.meta.url === pathToFileURL(process.argv[1]).href
if (isMain) {
    await start({
        filter: process.argv[2] || '',
        directoryPath: process.cwd(),
    })
}
