#!/usr/bin/env bash

. "$scripts/installer.sh"

installAzureCli() {
    curl -fsSL https://aka.ms/InstallAzureCLIDeb | bash || error "Failed to install Azure CLI"
    success "Installed Azure CLI"
}

install az installAzureCli
