#!/usr/bin/env bash

. "$scripts/installer.sh"

installAzCopy() {
    curl -sSL -O https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb
    dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb
    apt-get update
    apt-get install -y azcopy || error "Failed to install AzCopy"
    success "Installed AzCopy"
}

install azcopy installAzCopy
