#!/usr/bin/env bash

. "$scripts/installer.sh"

installDocker() {
    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/dockerArchiveKeyring.gpg
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/dockerArchiveKeyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io || error "Failed to install Docker"
    groupadd -f docker
    usermod -aG docker "$USER"
    success "Installed Docker"
}

install docker installDocker
