#!/usr/bin/env bash

. "$scripts/installer.sh"

installDocker() {
    local architecture
    local distribution
    local versionCodename

    . /etc/os-release
    architecture=$(dpkg --print-architecture)
    distribution="$ID"
    versionCodename="$VERSION_CODENAME"
    apt-get update -y
    apt-get install -y ca-certificates curl gnupg
    /usr/bin/install -m 0755 -d /etc/apt/keyrings
    curl -fsSL "https://download.docker.com/linux/$distribution/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$architecture signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$distribution $versionCodename stable" | tee /etc/apt/sources.list.d/docker.list >/dev/null
    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras
}

installRootlessPackages() {
    local package
    local packages=(
        dbus-user-session
        docker-ce-rootless-extras
        fuse-overlayfs
        slirp4netns
        uidmap
    )

    for package in "${packages[@]}"; do
        if ! dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -q 'install ok installed'; then
            apt-get install -y "${packages[@]}"
            return
        fi
    done
}

disableRootfulService() {
    local state
    local unit="$1"

    if systemctl is-active --quiet "$unit"; then
        systemctl stop "$unit" >/dev/null
    fi
    state=$(systemctl is-enabled "$unit" 2>/dev/null || true)
    if [[ "$state" != 'masked' ]]; then
        systemctl disable "$unit" >/dev/null 2>&1 || true
        systemctl mask "$unit" >/dev/null
    fi
}

install docker installDocker
installRootlessPackages
disableRootfulService docker.socket
disableRootfulService docker.service
disableRootfulService containerd.service
rm -f /var/run/docker.sock

. "$scripts/configureRootlessDocker.sh"

while IFS=: read -r user _ userId _ _ homeDir shell; do
    if [[ "$userId" -ge 1000 ]] && [[ "$homeDir" == /home/* ]] && [[ "$shell" != */nologin ]] && [[ "$shell" != */false ]]; then
        if getent group docker >/dev/null; then
            gpasswd -d "$user" docker >/dev/null 2>&1 || true
        fi
        configureRootlessDocker "$user"
    fi
done < /etc/passwd
