#!/usr/bin/env bash

. "$scripts/installer.sh"

installDockerCompose() {
    mkdir -p /usr/local/bin
    local latestVersion
    latestVersion=$(curl -fsSL https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*?)(?=")')
    if [[ -z "$latestVersion" ]]; then
        error "Failed to fetch the latest Docker Compose version"
    fi
    curl -fsSL "https://github.com/docker/compose/releases/download/${latestVersion}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose || error "Failed to install Docker Compose"
    success "Installed Docker Compose $latestVersion"
}

install docker-compose installDockerCompose
