#!/usr/bin/env bash
. "$scripts/installer.sh"
. "$scripts/logger.sh"

installNode() {
    info 'install node ...'
    apt-get update -y
    apt-get install -y curl ca-certificates gnupg jq
    curl -fsSL https://deb.nodesource.com/setup_lts.x |  -E bash -
    apt-get install -y nodejs

    echo 'export NODE_OPTIONS="--trace-deprecation"' >> ~/.bashrc
    export NODE_OPTIONS="--trace-deprecation"
}

latestLts=$(curl -s https://nodejs.org/dist/index.json)

if [[ -z "$latestLts" ]]; then
    error "Change your internet or DNS"
fi

latestLts=$(echo "$latestLts" | jq -r '[.[] | select(.lts != false)][0].version')

installedVersion=$(node --version 2>/dev/null || true)

if [[ "$installedVersion" == "$latestLts" ]]; then
    success "Node.js $checkMark"
else
    install node installNode
fi
