#!/usr/bin/env bash

. "$scripts/installer.sh"

installPm2() {
    npm install -g --registry='https://registry.npmjs.org' pm2
}

install pm2 installPm2

. "$scripts/configurePm2.sh"
. "$scripts/forEachDeploymentUser.sh"

forEachDeploymentUser configurePm2
