#!/usr/bin/env bash
set -euo pipefail

. "$scripts/installer.sh"

updateApt() {
    info "Updating apt ..."
    apt-get update || error "Failed to update apt"
    success "Updated apt"
}

setNginxDefaultSite() {
    if mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled-default-backup 2>/dev/null; then
        success "Moved default Nginx site to backup"
    else
        success "Default Nginx site $checkMark"
    fi

    local source="/holism/server/webServer/default"
    local target="/etc/nginx/conf.d/default.conf"

    if [ -L "$target" ] && [ "$(readlink -f "$target")" = "$(readlink -f "$source")" ]; then
        success "Nginx default link already exists $checkMark"
    else
        ln -sfn "$source" "$target"
        nginx -s reload
        success "Linked Nginx default site"
    fi
}

registerHolismCommands() {
    local bashLine='export PATH="/holism/server/commands:$PATH"'
    local environmentLine='PATH="/holism/server/commands:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'

    if grep -Fq '/holism/server/commands' /etc/environment; then
        sed -i "\|/holism/server/commands|c\\$environmentLine" /etc/environment
    else
        chmod 644 /etc/environment
        printf '%s\n' "$environmentLine" | tee -a /etc/environment > /dev/null
    fi
    if grep -Fq '/holism/server/commands' /etc/bash.bashrc; then
        sed -i "\|/holism/server/commands|c\\$bashLine" /etc/bash.bashrc
    else
        chmod 644 /etc/bash.bashrc
        printf '%s\n' "$bashLine" | tee -a /etc/bash.bashrc > /dev/null
    fi
    success "Registered Holism commands"
}

setTimeZone() {
    if timedatectl | grep -q "Time zone: UTC"; then
        success "Time Zone $checkMark"
        return
    fi
    info "Configuring Time Zone to UTC ..."
    timedatectl set-timezone UTC || error "Failed to set time zone"
    success "Configured Time Zone to UTC"
}

addSbinToUserPath() {
    local file="/etc/bash.bashrc"
    local line='export PATH=$PATH:/usr/sbin'

    if ! grep -Fxq "$line" "$file"; then
        echo "$line" | tee -a "$file" > /dev/null
        echo "/usr/sbin added to PATH in $file"
    fi
}

updateApt

install curl
install git
install jq
install nethogs
install rsync
install telnet
install unzip
install zip

$setupProd/nginx
$setupProd/certbot
$setupProd/htpasswd
setNginxDefaultSite

$setupProd/micro
$setupProd/rclone

# $setupProd/az
# $setupProd/azcopy

$setupProd/docker

$setupProd/node
$setupProd/pm2
npm install -g --registry='https://mirror-npm.runflare.com' serve

registerHolismCommands
setTimeZone
source "$setupProd/normalizeShells.sh"
addSbinToUserPath

source $setupProd/secureUsers.sh
source $setupProd/setPermissions.sh
$setupProd/includeUpdateTerminalTitleConfig.js

# apt-get -y install uidmap
# systemctl disable --now docker.service docker.socket
# rm /var/run/docker.sock

# per user:

# curl -fsSL https://get.docker.com/rootless | sh

# echo 'export XDG_RUNTIME_DIR=$HOME/.docker/run' >> ~/.bashrc
# echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
# echo 'export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock' >> ~/.bashrc

# mkdir -p $HOME/.docker/run
# chmod 700 $HOME/.docker/run

# mkdir -p ~/.config/docker
# micro ~/.config/docker/daemon.json
# {
#   "exec-opts": ["native.cgroupdriver=cgroupfs"]
# }

# dockerd-rootless.sh &

# for the entire server

# ------------------
# tee /etc/systemd/system/docker-rootless-all.service > /dev/null <<'EOF'
# [Unit]
# Description=Rootless Docker Daemon for all users
# After=network.target

# [Service]
# Type=forking
# ExecStart=/bin/bash -c '
# for dir in /home/*/.docker/run; do
#   user=$(basename $(dirname $dir))
#   export XDG_RUNTIME_DIR=$dir
#   export PATH=/home/$user/bin:/usr/bin:/bin
#   -u $user /home/$user/bin/dockerd-rootless.sh >/home/$user/.docker/dockerd.log 2>&1 &
# done
# wait
# '
# Restart=always
# RestartSec=10s

# [Install]
# WantedBy=multi-user.target
# EOF

# ---------------------------

# systemctl daemon-reload
# systemctl enable docker-rootless-all
# systemctl start docker-rootless-all
